// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import dotenv from 'dotenv';
import path from 'path';
import { defineConfig, env } from 'prisma/config';

// esta solucion es en caso que se elimine el .env que genera prisma, ya que el .env se encuentra en la raiz del proyecto y no en el paquete database, entonces al ejecutar los comandos de prisma no encuentra el .env y por ende no encuentra la variable de entorno DATABASE_URL, con esta solucion se le indica a dotenv que busque el .env en la raiz del proyecto y no en el paquete database
dotenv.config({
    path: path.resolve(import.meta.dirname, '../../.env'),
});

export default defineConfig({
    schema: 'prisma/schema.prisma',
    migrations: {
        path: 'prisma/migrations',
    },
    datasource: {
        url: env('DATABASE_URL'),
    },
});
